[package]
name = "gjtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo-types = "0.7.9"
geojson = "0.24.0"
geozero = { version = "0.9.7", features = ["with-wkb"] }
